name: Fetch Papers Daily

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:      # Enables manual trigger

jobs:
  fetch_papers:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests
      # run: pip install sentence-transformers

    - name: Run fetch script
      run: python fetch_papers.py

    - name: Commit and push JSON
      run: |         
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add papers.json
        git commit -m "Update papers"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
